apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: apppython
  namespace: dev
  annotations:
    argocd-image-updater.argoproj.io/image-list: myalias=garrijuan/${REPO} #mircroservertesting_dev
    argocd-image-updater.argoproj.io/myalias.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/myalias.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/myalias.update-strategy: latest
spec:
  replicas: 10
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: apppython
  template:
    metadata:
      labels:
        app: apppython
    spec:
      containers:
      - name: apppython
        image: garrijuan/mircroservertesting_dev:daigualpuestoqueimageupdaterlomachaca # Placeholder para que sea actualizado
        ports:
        - containerPort: 80
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: { duration: 30s }
      - setWeight: 50
      - pause: { duration: 30s }
      - setWeight: 100