apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "apppython.fullname" . }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx" 
spec:
  rules:
    - host: a7e5caf0b0ff24439a48331ac863e619-270330354.us-east-1.elb.amazonaws.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: apppython
                port:
                  number: 8081

