name: CI-PRO

on:
  pull_request:
    branches:
      - main



env:
    ENVIRONMENT: ${{ startsWith(github.ref, 'refs/heads/main') && 'pro' || 'dev' }}
      

jobs:
  test:
    name: python Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r apppython/app/requirements.txt

      - name: Run tests
        run: |
          python3 -m unittest apppython/test/test_main.py
          
### generar imagen docker y repositarla
  build_and_push_docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: test
    if: ${{ (github.event_name == 'push' || github.event_name == 'pull_request') && success() }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        if: ${{ env.ENVIRONMENT == 'dev' }}
        run: docker build -t mircroservertesting_dev -f apppython/Dockerfile apppython
      
      - name: Build Docker image
        if: ${{ env.ENVIRONMENT == 'pro' }}
        run: docker build -t mircroserver_pro -f apppython/Dockerfile apppython

      - name: Log into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Set short git commit SHA
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV

      - name: Tag Docker image to DEV
        if: ${{ env.ENVIRONMENT == 'dev' }}
        run: docker tag mircroservertesting_dev ${{ secrets.DOCKER_USERNAME }}/mircroservertesting_dev:${{ env.COMMIT_SHORT_SHA }}

      - name: Tag Docker image to PRO
        if: ${{ env.ENVIRONMENT == 'pro' }}
        run: docker tag mircroserver_pro ${{ secrets.DOCKER_USERNAME }}/mircroserver_pro:${{ env.COMMIT_SHORT_SHA }}


      - name: Push Docker image to DEV
        if: ${{ env.ENVIRONMENT == 'dev' }}
        run: docker push ${{ secrets.DOCKER_USERNAME }}/mircroservertesting_dev:${{ env.COMMIT_SHORT_SHA }}

      - name: Push Docker image to PRO
        if: ${{ env.ENVIRONMENT == 'pro' }}

        run: docker push ${{ secrets.DOCKER_USERNAME }}/mircroserver_pro:${{ env.COMMIT_SHORT_SHA }}

